### ISSUE TITLE
有论文吗

### ISSUE THREAD

**Issue by john826** [Derfei/Dependency-Aware-Computation-Offloading-for-Mobile-Edge-Computing-with-Edge-Cloud-Cooperation#1]

**Comment by Derfei** [comment]
论文已经发表在TCC上面online了

**Comment by john826** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Derfei/Dependency-Aware-Computation-Offloading-for-Mobile-Edge-Computing-with-Edge-Cloud-Cooperation"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月22日(星期天) 下午4:57
收件人:&nbsp;"Derfei/Dependency-Aware-Computation-Offloading-for-Mobile-Edge-Computing-with-Edge-Cloud-Cooperation"<Dependency-Aware-Computation-Offloading-for-Mobile-Edge-Computing-with-Edge-Cloud-Cooperation@noreply.github.com&gt;;
抄送:&nbsp;"学正"<644384120@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Derfei/Dependency-Aware-Computation-Offloading-for-Mobile-Edge-Computing-with-Edge-Cloud-Cooperation] 有论文吗 (#1)





 
Closed #1.
